# Generated by Django 4.1.7 on 2023-03-20 00:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_postmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(choices=[('tanks', 'Tanks'), ('healers', 'Heals'), ('dd', 'Damage Dealers'), ('vendors', 'Vendors'), ('guildmasters', 'Guildmasters'), ('quest_givers', 'Quest Givers'), ('blacksmiths', 'Blacksmiths'), ('leatherworkers', 'Leatherworkers'), ('potion_makers', 'Potion makers'), ('spell_masters', 'Spell masters')], default='dd', max_length=20, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
